# Generated by Django 4.1 on 2023-05-22 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.IntegerField(default=123456789, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(9)]),
            preserve_default=False,
        ),
    ]
