# Generated by Django 4.1 on 2023-05-09 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ads.currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='slug',
            field=models.SlugField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.IntegerField(max_length=18),
        ),
    ]
