# Generated by Django 4.1 on 2023-05-18 16:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_alter_ad_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=9000),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image2',
            field=models.ImageField(null=True, upload_to='ads/'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image3',
            field=models.ImageField(null=True, upload_to='ads/'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image4',
            field=models.ImageField(null=True, upload_to='ads/'),
        ),
    ]
